name: Build, Compress and Release minimap-gui

on:
  push:
    tags:
      - 'v*'  # 监听标签推送事件
  workflow_dispatch:  # 手动触发事件


jobs:
  build:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: write
      pages: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # 编译 Vue.js 项目

      - name: Compress build files
        run: zip -r minimap-gui-${{ github.ref_name || 'manual-build' }}.zip dist  # 手动触发时文件名默认 "manual-build"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name || 'manual-build' }}  # 没有标签时使用默认值
          release_name: Release ${{ github.ref_name || 'manual-build' }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MINIMAP_GUI_RELEASE }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MINIMAP_GUI_RELEASE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./minimap-gui-${{ github.ref_name || 'manual-build' }}.zip
          asset_name: minimap-gui-${{ github.ref_name || 'manual-build' }}.zip
          asset_content_type: application/zip
